In [2]:
import numpy as np

In [3]:
##Create a 1d array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#2d array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #1,5 means 1 row 5 columns
## or create nested list
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [5]:
np.arange(0,10,2).reshape(5,1) #5 rows 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Numpy Vectorized operation

In [8]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print("Multiplication", arr1 * arr2)

Multiplication [ 10  40  90 160 250]


In [9]:
#inbuilt numpy functions

arr = np.array([1,2,34,4,5])
print(np.sqrt(arr))
print(np.sin(arr))

[1.         1.41421356 5.83095189 2.         2.23606798]
[ 0.84147098  0.90929743  0.52908269 -0.7568025  -0.95892427]


In [15]:
#array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[0,10,11,12]])
print(arr)
arr[0][0]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 0 10 11 12]]


np.int64(1)

In [20]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [22]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
##Modify array elements
arr[0,0] = 100

In [24]:
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  0  10  11  12]]


In [28]:
##Statiscial concepts
##to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])
var = np.var(data)
mean = np.mean(data)
std_dev = np.std(data)
normalised_data = (data-mean)/std_dev
print("Normalised Data", normalised_data)

Normalised Data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [29]:
##Logical Operation

data>5

array([False, False, False, False, False])